Rulescard
SButterbluemchen/quidditch-club pull request #22
Opened 2022-04-13 19:21 UTC by Trixkiddo

- Un peu de CSS sur les cartes des règles du Quidditch
- Composant "broom title" réutilisable pour tous nos titres
- Certainement des passages pas en pur SASS, je ne maîtrise pas encore bien flexbox + SASS :) 
- Le composant Youtube a déjà été mergé, je l'ai récupéré de Dorothée. Je ne l'ai pas encore utilisé mais ça pourrait peut-être se réutiliser

2022-04-15 09:03 UTC, SButterbluemchen requested changes
Top ! J'avoue que je n'ai pas tout checker 100% en détail, mais ca me paraît canon ! 
Ca fait plaisir de voir un code si joli <3

2022-04-15 09:03 UTC, SButterbluemchen commented on src/stylesheets/pages/_history.scss
> +  justify-content: center;
Tu peux remplacer une grande partie avec mon mixin @include flex-wrap(...). :) Ca t'évite à tout écrire.

2022-04-15 09:03 UTC, SButterbluemchen commented on src/stylesheets/pages/_history.scss
> +  justify-content: center;
Attention, il y a un conflit apparement à résoudre avant pouvoir merger. J'espère que ca ne va rien casser.

2022-04-15 09:38 UTC, Trixkiddo commented on src/stylesheets/pages/_history.scss
> +  justify-content: center;
Ouii c'est vrai, j'oublie souvent ce mixin !

2022-04-19 13:35 UTC, SButterbluemchen approved these changes

2022-04-19 13:37 UTC, merged